=== BrielOtero/xml/03-sheet-dtd/03-exercise/exercise.dtd
<!ELEMENT coches (coche)+>
<!ELEMENT coche (matricula,marca,año,color,prox_revision)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT prox_revision (#PCDATA)>

=== BrielOtero/xml/03-sheet-dtd/03-exercise/exercise.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coches SYSTEM "exercise.dtd">
<coches>
	<coche>
		<matricula>8899JJJ</matricula>
		<marca>Citroen</marca>
		<a単o>2017</a単o>
		<color>Rojo</color>
		<prox_revision>22/07/2019</prox_revision>
	</coche>
	<coche>
		<matricula>PO-5555-BS</matricula>
		<marca>Rover</marca>
		<a単o>1999</a単o>
		<color>Azul</color>
		<prox_revision>22/03/2017</prox_revision>
	</coche>
</coches>
