=== BrielOtero/xml/csalud.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="csalud">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="medicos"></xs:element>
                <xs:element ref="pacientes"></xs:element>
                <xs:element ref="citas"></xs:element>                
            </xs:sequence>
        </xs:complexType>
    </xs:element>



    <xs:element name="medicos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="medico" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="identificador" type="Identificador"></xs:element>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="especialidad" type="xs:string"></xs:element>
                            <xs:element name="sala" type="xs:nonNegativeInteger"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pacientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paciente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DNI" type="dni"></xs:element>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="telefono" maxOccurs="3">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}\-\d{3}\-\d{3}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NUSS" type="xs:string"></xs:element>
                            <xs:element name="fechaNacimiento" type="xs:string"></xs:element>
                            <xs:element name="sexo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Hombre"></xs:enumeration>
                                        <xs:enumeration value="Mujer"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:nonNegativeInteger"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="citas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cita" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha" type="xs:string"></xs:element>
                            <xs:element name="identificador" type="Identificador" />
                            <xs:element name="DNI" type="dni"></xs:element>
                            <xs:element name="tratamiento" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="Identificador">
        <xs:restriction base="xs:string">
            <xs:pattern value="\w{5}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dni">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}([A-Z]|[a-z])"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== BrielOtero/xml/05-xml-shemes/02-exercise/csalud.xml
<?xml version="1.0" encoding="UTF-8"?>
<csalud xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="csalud.xsd">
<medicos>
    <medico>
        <identificador>rt5ud</identificador>
        <nombre>Juan</nombre>
        <especialidad>Traumatología</especialidad>
        <sala>1</sala>
    </medico>
    <medico>
        <identificador>rt5ud</identificador>
        <nombre>Juan</nombre>
        <especialidad>Traumatología</especialidad>
        <sala>1</sala>
    </medico>
</medicos>
<pacientes>
    <paciente id="1">
        <DNI>12345678a</DNI>
        <nombre></nombre>
        <direccion>
        </direccion>
        <telefono>555-555-555</telefono>
        <telefono>999-444-333</telefono>
        <NUSS></NUSS>
        <fechaNacimiento></fechaNacimiento>
        <sexo>Hombre</sexo>
    </paciente>
    <paciente>
        <DNI>12345678a</DNI>
        <nombre></nombre>
        <direccion>
        </direccion>
        <telefono>555-555-555</telefono>
        <telefono>999-444-333</telefono>
        <NUSS></NUSS>
        <fechaNacimiento></fechaNacimiento>
        <sexo>Hombre</sexo>
    </paciente>
</pacientes>
<citas>
    <cita>
        <fecha></fecha>
        <identificador>r555t</identificador>
        <DNI>12345678A</DNI>
        <tratamiento></tratamiento>
    </cita>
    <cita>
        <fecha></fecha>
        <identificador>r555t</identificador>
        <DNI>12345678A</DNI>
        <tratamiento></tratamiento>
    </cita>
</citas>


</csalud>
