=== BrielOtero/xml/02-sheet-xml/06-exercise/exercise.dtd
<!ELEMENT listafacturas (facturas+)>
<!ELEMENT facturas (emisor+,pagador+,importe+)>
<!ATTLIST facturas fecha CDATA #REQUIRED>
<!ATTLIST emisor cif CDATA #REQUIRED>
<!ATTLIST pagador cif CDATA #REQUIRED>
<!ELEMENT emisor (nombre+,volumenventas?)>
<!ELEMENT pagador (nombre+,volumenventas?)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT volumenventas (#PCDATA)>

=== BrielOtero/xml/02-sheet-xml/06-exercise/exercise.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listafacturas PUBLIC "public-id" "exercise.dtd">
<listafacturas>
	<facturas fecha="hello">
		<emisor cif="77777777">
			<nombre></nombre>
			<volumenventas></volumenventas>
		</emisor>
		<pagador cif="7777777777">
			<nombre></nombre>
			<volumenventas></volumenventas>
		</pagador>
		<importe></importe>
	</facturas>
</listafacturas>
