=== BrielOtero/xml/04-shemes/05-exercise/exercise.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pedido">
		<xs:complexType>
		
			<xs:sequence>
				<xs:element name="cliente" maxOccurs="1"></xs:element>
				<xs:element name="envio">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="direccion" type="xs:string"></xs:element>
							<xs:element name="ciudad" type="xs:string"></xs:element>
							<xs:element name="pais" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="articulo" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="descripcion" type="xs:string"></xs:element>
							<xs:element name="nota" type="xs:string" minOccurs="0"></xs:element>
							<xs:element name="unidades" type="xs:string"></xs:element>
							<xs:element name="precio" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ordenid" type="xs:integer"></xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BrielOtero/xml/04-shemes/05-exercise/exercise.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedido ordenid="889923" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exercise.xsd">
	<cliente>Roberto Castro</cliente>
	<envio>
		<direccion>Principe 17</direccion>
		<ciudad>36202 Vigo</ciudad>
		<pais>España</pais>
	</envio>
	<articulo>
		<descripcion>Vela aromática</descripcion>
		<nota>Edición Espacial</nota>
		<unidades>1</unidades>
		<precio>10.90</precio>
	</articulo>
	<articulo>
		<descripcion>Espejo de bolso</descripcion>
		<unidades>1</unidades>
		<precio>9.90</precio>
	</articulo>
</pedido>
