=== BrielOtero/xml/03-sheet-dtd/04-exercise/02-exercise-case.dtd
<!ELEMENT libros (libro)*>
<!ELEMENT libro (título,autor,num_pags,editorial)> 
<!ELEMENT título (#PCDATA)> 
<!ELEMENT autor (#PCDATA)> 
<!ELEMENT num_pags (#PCDATA)> 
 <!ELEMENT editorial (#PCDATA)>

=== BrielOtero/xml/03-sheet-dtd/04-exercise/02-exercise-case.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "02-exercise-case.dtd">
<libros>
	<libro>
		<título></título>
		<autor></autor>
		<num_pags></num_pags>
		<editorial></editorial>
	</libro>
	<libro>
		<título></título>
		<autor></autor>
		<num_pags></num_pags>
		<editorial></editorial>
	</libro>
</libros>
